language: node_js
node_js:
 - node
install:
 - npm install
services:
 - postgresql

before_script:
 - psql -c 'CREATE DATABASE way_farer;' -U postgres
script:
 - npm run test
after_success:
 - npm run coveralls